/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import Modelo.Modelo;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author PC01
 */
public class Vista extends javax.swing.JFrame {

    int xMouse, yMouse;
    private Modelo modelo = new Modelo();
    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
        BtnAgregar.setBackground(Color.white);
        LAgregar.setForeground(Color.black);
        PanelAgregar.setVisible(true);
        PanelConsultar.setVisible(false);
        TxtBuscar.setText("");
        Limpiar();


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        MenuOpciones = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        BtnConsultar = new javax.swing.JPanel();
        LConsulta = new javax.swing.JLabel();
        BtnAgregar = new javax.swing.JPanel();
        LAgregar = new javax.swing.JLabel();
        BarraSuperior = new javax.swing.JPanel();
        Cerrar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Minimizar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        BarraSuperior2 = new javax.swing.JPanel();
        PanelAgregar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        TxtNombre = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        TxtApaterno = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        TxtAmaterno = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        TxtCalle = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        TxtNumero = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        TxtColonia = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        BtnGuardar = new javax.swing.JButton();
        PanelConsultar = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        TxtConsultarNombre = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        TxtConsultarCalle = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        TxtConsultarNumero = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        TxtConsultarColonia = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        PanelBuscar = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jSeparator11 = new javax.swing.JSeparator();
        TxtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Practica2");
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MenuOpciones.setBackground(new java.awt.Color(64, 83, 255));
        MenuOpciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuOpcionesMouseClicked(evt);
            }
        });
        MenuOpciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("       Menú");
        MenuOpciones.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 50));

        BtnConsultar.setBackground(new java.awt.Color(64, 83, 255));
        BtnConsultar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LConsulta.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        LConsulta.setForeground(new java.awt.Color(255, 255, 255));
        LConsulta.setText("    Consultar");
        BtnConsultar.add(LConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 40));

        MenuOpciones.add(BtnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 140, 40));

        BtnAgregar.setBackground(new java.awt.Color(64, 83, 255));
        BtnAgregar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LAgregar.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        LAgregar.setForeground(new java.awt.Color(255, 255, 255));
        LAgregar.setText("      Agregar");
        LAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LAgregarMouseClicked(evt);
            }
        });
        BtnAgregar.add(LAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 40));

        MenuOpciones.add(BtnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 140, 40));

        jPanel1.add(MenuOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 480));

        BarraSuperior.setBackground(new java.awt.Color(255, 255, 255));
        BarraSuperior.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Cerrar.setBackground(new java.awt.Color(255, 255, 255));
        Cerrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel1.setText("    X");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });
        Cerrar.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 30));

        BarraSuperior.add(Cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 0, 40, 30));

        Minimizar.setBackground(new java.awt.Color(255, 255, 255));
        Minimizar.setPreferredSize(new java.awt.Dimension(27, 22));
        Minimizar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel3.setText("   _");
        jLabel3.setMaximumSize(new java.awt.Dimension(27, 22));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });
        Minimizar.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        BarraSuperior.add(Minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(603, 0, 30, 30));

        BarraSuperior2.setBackground(new java.awt.Color(255, 255, 255));
        BarraSuperior2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BarraSuperior2MouseDragged(evt);
            }
        });
        BarraSuperior2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BarraSuperior2MousePressed(evt);
            }
        });

        javax.swing.GroupLayout BarraSuperior2Layout = new javax.swing.GroupLayout(BarraSuperior2);
        BarraSuperior2.setLayout(BarraSuperior2Layout);
        BarraSuperior2Layout.setHorizontalGroup(
            BarraSuperior2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        BarraSuperior2Layout.setVerticalGroup(
            BarraSuperior2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        BarraSuperior.add(BarraSuperior2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 30));

        jPanel1.add(BarraSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 30));

        PanelAgregar.setBackground(new java.awt.Color(255, 255, 255));
        PanelAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelAgregarMouseClicked(evt);
            }
        });
        PanelAgregar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel2.setText("Nombre");
        PanelAgregar.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, 20));

        TxtNombre.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        TxtNombre.setText("jTextField1");
        TxtNombre.setAutoscrolls(false);
        TxtNombre.setBorder(null);
        PanelAgregar.add(TxtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 280, 20));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        PanelAgregar.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 270, 10));

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel5.setText("Apellido Paterno");
        PanelAgregar.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, 20));

        TxtApaterno.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        TxtApaterno.setText("jTextField1");
        TxtApaterno.setAutoscrolls(false);
        TxtApaterno.setBorder(null);
        TxtApaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtApaternoActionPerformed(evt);
            }
        });
        PanelAgregar.add(TxtApaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 280, 20));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        PanelAgregar.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 260, 10));

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel6.setText("Apellido Materno");
        PanelAgregar.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, 20));

        TxtAmaterno.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        TxtAmaterno.setText("jTextField1");
        TxtAmaterno.setAutoscrolls(false);
        TxtAmaterno.setBorder(null);
        TxtAmaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtAmaternoActionPerformed(evt);
            }
        });
        PanelAgregar.add(TxtAmaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 280, 20));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        PanelAgregar.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 270, 10));

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel7.setText("Calle");
        PanelAgregar.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, 20));

        TxtCalle.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        TxtCalle.setText("jTextField1");
        TxtCalle.setAutoscrolls(false);
        TxtCalle.setBorder(null);
        TxtCalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCalleActionPerformed(evt);
            }
        });
        PanelAgregar.add(TxtCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 330, 20));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        PanelAgregar.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 330, 10));

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel8.setText("Número");
        PanelAgregar.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, 20));

        TxtNumero.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        TxtNumero.setText("jTextField1");
        TxtNumero.setAutoscrolls(false);
        TxtNumero.setBorder(null);
        TxtNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNumeroActionPerformed(evt);
            }
        });
        PanelAgregar.add(TxtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 80, 20));

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        PanelAgregar.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 80, 10));

        jLabel9.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel9.setText("Colonia");
        PanelAgregar.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, 20));

        TxtColonia.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        TxtColonia.setText("jTextField1");
        TxtColonia.setAutoscrolls(false);
        TxtColonia.setBorder(null);
        TxtColonia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtColoniaActionPerformed(evt);
            }
        });
        PanelAgregar.add(TxtColonia, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 320, 20));

        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        PanelAgregar.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 320, 10));

        BtnGuardar.setBackground(new java.awt.Color(64, 83, 255));
        BtnGuardar.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        BtnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        BtnGuardar.setText("Guardar");
        BtnGuardar.setBorder(null);
        BtnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnGuardarMouseClicked(evt);
            }
        });
        BtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarActionPerformed(evt);
            }
        });
        PanelAgregar.add(BtnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 323, 90, 30));

        jPanel1.add(PanelAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 530, 450));

        PanelConsultar.setBackground(new java.awt.Color(255, 255, 255));
        PanelConsultar.setEnabled(false);
        PanelConsultar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel11.setText("Nombre");
        PanelConsultar.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, 20));

        TxtConsultarNombre.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        TxtConsultarNombre.setText("jTextField1");
        TxtConsultarNombre.setBorder(null);
        TxtConsultarNombre.setEnabled(false);
        PanelConsultar.add(TxtConsultarNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 400, -1));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        PanelConsultar.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 400, 10));

        jLabel12.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel12.setText("Calle");
        PanelConsultar.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, 20));

        TxtConsultarCalle.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        TxtConsultarCalle.setText("jTextField1");
        TxtConsultarCalle.setBorder(null);
        TxtConsultarCalle.setEnabled(false);
        PanelConsultar.add(TxtConsultarCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 400, -1));

        jSeparator8.setForeground(new java.awt.Color(0, 0, 0));
        PanelConsultar.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 400, 10));

        jLabel14.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel14.setText("Numero");
        PanelConsultar.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, 20));

        TxtConsultarNumero.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        TxtConsultarNumero.setText("jTextField1");
        TxtConsultarNumero.setBorder(null);
        TxtConsultarNumero.setEnabled(false);
        PanelConsultar.add(TxtConsultarNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 100, -1));

        jSeparator9.setForeground(new java.awt.Color(0, 0, 0));
        PanelConsultar.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 100, 10));

        TxtConsultarColonia.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        TxtConsultarColonia.setText("jTextField1");
        TxtConsultarColonia.setBorder(null);
        TxtConsultarColonia.setEnabled(false);
        PanelConsultar.add(TxtConsultarColonia, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 400, -1));

        jSeparator10.setForeground(new java.awt.Color(0, 0, 0));
        PanelConsultar.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 400, 10));

        jLabel15.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel15.setText("Colonia");
        jLabel15.setToolTipText("");
        PanelConsultar.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, 20));

        PanelBuscar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel17.setText("Buscar Id proveedor");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 40));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 140, 40));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator11.setBackground(new java.awt.Color(0, 0, 0));
        jPanel6.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 250, 10));

        TxtBuscar.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        TxtBuscar.setText("jTextField1");
        TxtBuscar.setBorder(null);
        TxtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtBuscarActionPerformed(evt);
            }
        });
        jPanel6.add(TxtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 250, 30));

        btnBuscar.setBackground(new java.awt.Color(64, 83, 255));
        btnBuscar.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.setBorder(null);
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel6.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 100, 30));

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 390, 40));

        PanelBuscar.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 550, 50));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        PanelBuscar.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 30));

        PanelConsultar.add(PanelBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 70));

        jPanel1.add(PanelConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 550, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void Limpiar(){
        TxtNombre.setText("");
        TxtApaterno.setText("");
        TxtAmaterno.setText("");
        TxtCalle.setText("");
        TxtNumero.setText("");
        TxtColonia.setText("");
    }
    private void BarraSuperior2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraSuperior2MousePressed
        xMouse= evt.getX();        
        yMouse= evt.getY();

    }//GEN-LAST:event_BarraSuperior2MousePressed

    private void BarraSuperior2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraSuperior2MouseDragged
        //la ventana se mueve de manera normal
        int x,y;
        
        x=evt.getXOnScreen();        
        y=evt.getYOnScreen();

        this.setLocation(x - xMouse, y - yMouse);        
    }//GEN-LAST:event_BarraSuperior2MouseDragged

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        Cerrar.setBackground(Color.red);
        jLabel1.setForeground(Color.white);
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
               Cerrar.setBackground(Color.white);
               jLabel1.setForeground(Color.black);

    }//GEN-LAST:event_jLabel1MouseExited

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        this.setExtendedState(1);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void TxtApaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtApaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtApaternoActionPerformed

    private void TxtAmaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtAmaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtAmaternoActionPerformed

    private void TxtCalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCalleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCalleActionPerformed

    private void TxtNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNumeroActionPerformed

    private void TxtColoniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtColoniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtColoniaActionPerformed

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        Minimizar.setBackground(new java.awt.Color(210,210,210));
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        Minimizar.setBackground(Color.white);
    }//GEN-LAST:event_jLabel3MouseExited

    private void PanelAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelAgregarMouseClicked
       
    }//GEN-LAST:event_PanelAgregarMouseClicked

    private void LAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LAgregarMouseClicked
        BtnAgregar.setBackground(new java.awt.Color(255,255,255));
        LAgregar.setForeground(Color.black);
        PanelAgregar.setVisible(true);
        
        
        BtnConsultar.setBackground(new java.awt.Color(64,83,255));
        LConsulta.setForeground(Color.white);
        PanelConsultar.setVisible(false);
    }//GEN-LAST:event_LAgregarMouseClicked

    private void MenuOpcionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuOpcionesMouseClicked
            BtnConsultar.setBackground(new java.awt.Color(255,255,255));
            LConsulta.setForeground(Color.black);
            PanelConsultar.setVisible(true);
            TxtConsultarNombre.setText("");
            TxtConsultarCalle.setText("");
            TxtConsultarNumero.setText("");
            TxtConsultarColonia.setText("");
        
        BtnAgregar.setBackground(new java.awt.Color(64,83,255));
        LAgregar.setForeground(Color.white);
        PanelAgregar.setVisible(false);
    }//GEN-LAST:event_MenuOpcionesMouseClicked

    private void TxtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtBuscarActionPerformed

    private void BtnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnGuardarMouseClicked
        try { 
            if(modelo.InsertarProveedor(this.TxtNombre.getText(), this.TxtApaterno.getText(), this.TxtAmaterno.getText(),
                    this.TxtCalle.getText(), this.TxtNumero.getText(), this.TxtColonia.getText()))
            {
                JOptionPane.showMessageDialog(null, "Registro agregado exitosamente");
                
                this.Limpiar();
            }
        } catch (SQLException ex) {
            Logger.getLogger(Vista.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnGuardarMouseClicked

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void BtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BarraSuperior;
    private javax.swing.JPanel BarraSuperior2;
    public javax.swing.JPanel BtnAgregar;
    public javax.swing.JPanel BtnConsultar;
    public javax.swing.JButton BtnGuardar;
    private javax.swing.JPanel Cerrar;
    public javax.swing.JLabel LAgregar;
    public javax.swing.JLabel LConsulta;
    private javax.swing.JPanel MenuOpciones;
    private javax.swing.JPanel Minimizar;
    private javax.swing.JPanel PanelAgregar;
    private javax.swing.JPanel PanelBuscar;
    private javax.swing.JPanel PanelConsultar;
    public javax.swing.JTextField TxtAmaterno;
    public javax.swing.JTextField TxtApaterno;
    public javax.swing.JTextField TxtBuscar;
    public javax.swing.JTextField TxtCalle;
    public javax.swing.JTextField TxtColonia;
    public javax.swing.JTextField TxtConsultarCalle;
    public javax.swing.JTextField TxtConsultarColonia;
    public javax.swing.JTextField TxtConsultarNombre;
    public javax.swing.JTextField TxtConsultarNumero;
    public javax.swing.JTextField TxtNombre;
    public javax.swing.JTextField TxtNumero;
    public javax.swing.JButton btnBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    // End of variables declaration//GEN-END:variables
}
